language: java
jdk:
- oraclejdk8
before_install:
- git config --global user.email "builds@travis-ci.com"
- git config --global user.name "Travis CI"
- if [[ $TRAVIS_PULL_REQUEST == "false" && $TRAVIS_BRANCH == "master" ]]; then git checkout master; fi
before_script:
- if [[ $TRAVIS_COMMIT_MESSAGE =~ .*doRelease.* || $TRAVIS_PULL_REQUEST == "false" && $TRAVIS_BRANCH == "master" ]]; then ./mvnw initialize -Pversion; fi
script:
- if [[  $TRAVIS_COMMIT_MESSAGE =~ .*doRelease.* || $TRAVIS_PULL_REQUEST == "false" && $TRAVIS_BRANCH == "master" ]]; then ./mvnw deploy --settings .mvn/settings.xml; else ./mvnw install; fi
branches:
  except:
  - /^v\d+\-b\d+$/
cache:
  directories:
  - "~/.m2/repository"
  - "~/.m2/wrapper"
install: true
env:
  global:
  - secure: "Nip2BbVsBfqai0/SMK+QolvuzWfcvVp5eGyYU7V9ysE+kbxm/DZm5kcAYh2SbipGRmTT6kdOMeK57Y4h11CpzF3XcR70La1d9v+OVv1JAuBjrgc3iAPxP05FgnzZA/Vp8glI6VT4vtklLLwI9P40PO8b1x48LdOWzPSPAn3CIPy/LR9TfEgRZotDUSGbVFUn6/u4w2I9eHch5Q5/Aj0jnNouZr1wDhhuI7Decp9ZrIW0QBFfu5vfyr6DJPEYgBrraH7rvketm7fRTdq8/RRno4p+owb8NZTRl1DyTRKNsUqbNdBb46SYcq49+oPoHm3GuGey4tbzOfIjaK8l12Nrupvff6T3iBLYSbxinxHxhzQcRltUs1J1Qpanr/x4X21qVxCoK4VPPMpqO2i+hKDyQBIx7YOx02BI0jH3+8YixLJM2HSdv80mxpQox0yyuTKcAZzE7XAqWEEcDE2xp1274U2+XUtdVOPkH66ll8ozIosBYiDkraOEQ1Osowt3eTx4uNQLtReaVZtapg18pdHlnwz/Mv1KkoqmVLsilPDbOW7zvyCic5vZm0N89SKqQHefQ1aAK26rVkMVV7J5nXPl+r35XzrDuPvJk6J4l5syCdZaZAEDg2y5cX0iXzkflJcBur6RLs6w3bXbTxyShzB04Y7ieNE9cZWc09ssQlLr66c="
